### PR TITLE
add Pool.{fetch{,row,val},execute{,many}}

### PR DESCRIPTION
**Pull request by bmintz**
Implements #2

### CODE REVIEW

**Comment by njsmith** [comment]
@touilleMan are you still using/maintaining this?

**Comment by bmintz** [comment]
I would be willing to take it over, if not.

**Comment by touilleMan** [comment]
@njsmith I'm still using this library

@bmintz every help is welcomed ! if @njsmith is ok we can add you to the trio organization 😃

**Comment by njsmith** [comment]
@touilleMan Cool! Just wanted to check b/c I wasn't sure what was going on :-).

And re: inviting @bmintz: Just merge the PR, and that will trigger the invitation :-)

**Comment by njsmith** [comment]
@bmintz Sorry, my attention is pretty taken up right now by trio proper and HTTP client stuff, so I can't really review this properly myself. But I don't want to leave you hanging, and @touilleMan said lgtm, so I guess I'll hit the merge button :-). Once its merged, our bot should automatically send you an invitation to join the org. And maybe you and @touilleMan can work out between yourselves how you want to handle your other PR, and future PRs?

**Comment by cpdean** [comment]
I'm really glad to see that this PR merged! it adds a lot of good quality-of-life improvements to triopg around connection pooling and running queries concurrently.  

I see that the latest version appears to be `triopg==0.3.0`, which does not have these changes included.  Is there something I can do to help out with releasing a new version of this package?

**Comment by iomintz** [comment]
@cpdean I've tagged v0.4.0, but I'll need someone else (likely @touilleMan) to upload to PyPI.

**Comment by touilleMan** [comment]
@iomintz I've done the v0.4.0 release 🎉

**Pull request merged**
